# Generated by Django 3.2.12 on 2024-03-11 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('platform', models.CharField(choices=[('PS5', 'PlayStation 5'), ('Xbox One', 'Xbox One'), ('Switch', 'Nintendo Switch'), ('PC', 'Personal Computer'), ('Others', 'Others')], default='Others', max_length=20)),
                ('genre', models.CharField(choices=[('Shooter', 'Shooter'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('RPG', 'Role-playing Game'), ('Others', 'Others')], default='Others', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_in_stock', models.IntegerField(default=0)),
                ('users_basket', models.ManyToManyField(blank=True, related_name='basket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
