# Generated by Django 3.2.12 on 2024-03-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
