# Generated by Django 3.2.12 on 2024-03-11 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0004_auto_20240311_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='users_basket',
            field=models.ManyToManyField(blank=True, related_name='basket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BasketItem',
        ),
    ]
